### ISSUE TITLE
characters information edit

### ISSUE THREAD

**Issue by gpedro** [opentibiabr/canaryaac#2]
steps to reproduce:
log in, edit an character, mark all checkboxes on "Edit Character Information" section, press submit. unmark all checkboxes and press submit.

----
- [ ] missing feedback on submit
- [ ] ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'account' at row 1

**Comment by libergod** [comment]
Hi, 

Identified and checking. Will be opening an PR quick.

1) Problem with check boxes, wich returned the error:
PROBLEM:
ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'account' at row 1

CAUSE:
When you have checkboxes, for some reason, if you didn't flag then, it will never come in the request. So, for some people works putting one more input checkbox hidden with default value 0, for me it didn't work, so i've made an logic in the Controller.
![image](https://user-images.githubusercontent.com/37589902/233178975-9507282b-3c93-4de3-80eb-30969b866363.png)

SOLUTION:
I know this isn't the best solution, but works. Later we can get this better. The main solution is validate if the postVars are being set. If not, we put a 0 on then.
![image](https://user-images.githubusercontent.com/37589902/233179599-1da25d9f-f0f1-4a29-a786-88036742f695.png)


2) Missing status feedback on submit

Currently working on it.
