### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by mynothingg** [opentibiabr/canaryaac#7]
When I access the home page it works perfectly, but when I click on any menu on the left side (e.g. characters, worlds, highscores) it always returns the 404 error. I didn't find anything useful in the Nginx LOG and I have already tried changing permissions in the folder where the site is located but without success.

OS: Ubuntu 22.04.2 LTS ARM64
nginx version: nginx/1.18.0
PHP 8.2.5 (cli) (built: Apr 14 2023 04:27:02)
<img width="1466" alt="Captura de Tela 2023-05-04 às 19 04 48" src="https://user-images.githubusercontent.com/26652894/236341253-e58a63f4-8ec8-469b-9811-4a7223183373.png">

<img width="1468" alt="Captura de Tela 2023-05-04 às 19 05 02" src="https://user-images.githubusercontent.com/26652894/236341291-d0acb104-edfc-41f7-a8c4-de826e74a85d.png">

**Comment by beats-dh** [comment]
@mynothingg 
Replace the contents of the `defaul` nginx configuration file with:
```
erver {
    listen       80;
    listen       [::]:80;
#   listen       443 ssl http2;
#   listen       [::]:443 ssl http2;

    server_name _;
#   server_name example.com  www.example.com;
    
    root   /var/www/html/;
    index index.php index.html index.htm;

#   if ($host !~ ^(exemple.com|www.example.com)$){
#       return 400;
#   }

    if ($request_method !~ ^(GET|HEAD|POST)$) {
        return 444;
    }
    
    location ~ /system {
        deny all;
        return 404;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ /\.git {
        return 403;
    }

    location ~* \.(pl|cgi|py|sh|lua)\$ {
        return 403;
    }

    location ~* ^/wp-content/uploads/.*.(asp|cgi|htm|html|js|jsp|php|pl|py|sh|shtml|swf)$ {
        return 403;
    }

    location ~* ^/(readme|license|schema|password|passwords).*.(txt|html)$ {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
#       try_files $uri $uri/ /index.php;
    }

    location ~ ^/(conf|doc|sql|setup)/ {
        deny all;
        return 403;
    }

#   Pass PHP Scripts To FastCGI Server
    location ~ \.php$ {
#       root /var/www/html/;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}```
